## NUMPY
NumPy provides an ** N-dimensional array type**, the ndarray, which describes a collection of “items” of the same type. The items can be indexed using for example N integers.

All ndarrays are homogenous: every item takes up the same size block of memory, and all blocks are interpreted in exactly the same way. How each item in the array is to be interpreted is specified by a separate data-type object, one of which is associated with every array. In addition to basic types (integers, floats, etc.), the data type objects can also represent data structures.

An item extracted from an array, e.g., by indexing, is represented by a Python object whose type is one of the array scalar types built in NumPy. The array scalars allow easy manipulation of also more complicated arrangements of data.

## ndarray

An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its *shape*, which is a tuple of N positive integers that specify the sizes of each dimension. The type of items in the array is specified by a separate data-type object (dtype), one of which is associated with each ndarray.

As with other container objects in Python, the contents of an ndarray can be accessed and modified by indexing or slicing the array (using, for example, N integers), and via the methods and attributes of the ndarray.

Different ndarrays can share the same data, so that changes made in one ndarray may be visible in another. That is, an ndarray can be a “view” to another ndarray, and the data it is referring to is taken care of by the “base” ndarray. ndarrays can also be views to memory owned by Python strings or objects implementing the buffer or array interfaces.

  

In [1]:
import numpy as np
print(np.__version__)

1.16.5


In [2]:
#creating  one dimensional array
a=np.array([1,2,3])
b=np.array( [[1,2,3],[11,22,33]])
print (a)
print(b)


[1 2 3]
[[ 1  2  3]
 [11 22 33]]


In [5]:
#find the no of dimensions in array
a.ndim


1

In [6]:
#find the shape of array
#which is a tuple of N positive integers that specify the sizes of each dimension.
print("shape", b.shape)
 
print("size", b.size)
print("item size", b.itemsize)
#a.shape
 


shape (2, 3)
size 6
item size 4


In [7]:
a.dtype

dtype('int32')

In [9]:
a*10

array([10, 20, 30])

# Creating Arrays

Easiest way of creating  arrays is using an **array** function.
This accepts many sequence like objects(including other arrays)  and produce
a new numpy array containing the passed data.

In [11]:
#creating with a list
d_lst=[2,4,6,8,10]
a=np.array(d_lst)

In [12]:
print (a)

[ 2  4  6  8 10]


In [13]:
d_lst=[[1,2,3],[4,5,6]]
b=np.array(d_lst)
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
print(b.ndim)
print(b.dtype)
print(b.shape)
print(b*10)

2
int32
(2, 3)
[[10 20 30]
 [40 50 60]]


In [15]:
#create an array using arange
x = np.arange(10)
print(x)
print(x.shape)
print(x.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
int32


In [16]:
#np.random.rand(shape)
x = np.random.rand(2,3)  # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary
x

array([[0.20761749, 0.66380855, 0.43935924],
       [0.68961177, 0.77852141, 0.20277718]])

In [17]:
#create an array using random values
x = np.random.rand(10)
print(x)
print(x.shape)
print(x.dtype)

[0.66012872 0.84122243 0.49745274 0.21871989 0.31223206 0.28854168
 0.08392955 0.09631978 0.99245446 0.51881853]
(10,)
float64


In [19]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 2.07864755 -1.63700474  0.89596435]
 [ 0.61174557 -1.17973104 -0.26752728]
 [ 1.09521102 -0.22197703 -1.09455973]
 [-0.84024503 -0.81814033 -0.87118497]]


In [20]:
print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random integer vector: [80 27  3 11 75 81 95 70 63 60]

Random integer matrix
[[50 68 18 89]
 [ 5 11 55  8]
 [55 10 43 46]
 [13 34 19 83]]

20 samples drawn from a dice throw: [5 1 4 4 4 6 2 2 3 3 6 2 5 4 2 2 1 6 6 1]


## numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

In [ ]:
# 21 linearly spaced  numbers between  1 and 5
la=np.linspace(1,5,21)
print(la)

In [ ]:
#creation of random values based on logscale 
#numpy.logspace(start,stop,num,endpoint,base, dtype)
#num is number of samples
#endpoint=True means last value will be included in output
#base : default is 10.0
z=np.logspace(1,10, num=5, endpoint=True, base=10.0)
z




## Ones and zeros
empty(shape[, dtype, order])	Return a new array of given shape and type, without initializing entries.

empty_like(a[, dtype, order, subok])	Return a new array with the same shape and type as a given array.

eye(N[, M, k, dtype, order])	Return a 2-D array with ones on the diagonal and zeros elsewhere.

identity(n[, dtype])	Return the identity array.

ones(shape[, dtype, order])	Return a new array of given shape and type, filled with ones.

ones_like(a[, dtype, order, subok])	Return an array of ones with the same shape and type as a given array.

zeros(shape[, dtype, order])	Return a new array of given shape and type, filled with zeros.

zeros_like(a[, dtype, order, subok])	Return an array of zeros with the same shape and type as a given array.

full(shape, fill_value[, dtype, order])	Return a new array of given shape and type, filled with fill_value.

full_like(a, fill_value[, dtype, order, subok])	Return a full array with the same shape and type as a given array.

In [ ]:
#zeros and ones create array of a given shape
np.zeros(10)

In [ ]:
np.ones(5)

In [ ]:
#pass a tuple for shape
np.zeros((3,6))

In [ ]:
np.zeros((3,6),dtype='int32')

In [22]:
#empty creates an array of the given shape. but filled with uninitialized garbage values
new=np.empty((3,2))
new

array([[0.20761749, 0.66380855],
       [0.43935924, 0.68961177],
       [0.77852141, 0.20277718]])

In [ ]:
#use zeros_like  or ones_like
np.ones_like(new)

In [21]:
#Return a new array of given shape and type, filled with fill_value.
np.full((3, 5), 8, dtype=int)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [ ]:
#arange is numpy range function
np.arange(10)

In [ ]:
#can specify datatype too
y=np.arange(3, dtype=np.float)
y

In [ ]:
#create identity  array
np.eye(2)

In [ ]:
#if you  need  a specific shape other than square matrix
np.eye(2,3)

In [ ]:
np.identity(3)

In [ ]:
#if you other than square, you get error
#np.identity(2,3)

# Mathematical methods
add(array1, array2) or use + , 
sub(array1,array2)  or use -, 
multiply(array1,array2)  or use * ,
divide(array1,array2) or use /.

In [ ]:
print('Add the two arrays:' )
print(np.add(a,b))
print(a+b)
print(a-b)
 

## Scalars
Python defines only one type of a particular data class (there is only one integer type, one floating-point type, etc.). This can be convenient in applications that don’t need to be concerned with all the ways data can be represented in a computer. For scientific computing, however, more control is often needed.

In NumPy, there are 24 new fundamental Python types to describe different types of scalars. These type descriptors are mostly based on the types available in the C language that CPython is written in, with several additional types compatible with Python’s types.

Array scalars have the same attributes and methods as ndarrays. This allows one to treat items of an array partly on the same footing as arrays, smoothing out rough edges that result when mixing scalar and array operations

In [ ]:
#A NumPy scalar is any object which is an instance of np.generic or whose type is in np.
##operations between arrays any scalars

a=np.ones((2,3))
a *4


In [ ]:
a*a

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
b

In [ ]:
b*b

In [ ]:
b**0.5

In [ ]:
b*10

## Single element indexing
Single element indexing for a 1-D array is what one expects. It work exactly like that for other standard Python sequences.
It is 0-based, and accepts negative indices for indexing from the end of the array.

In [ ]:
x = np.arange(10)
x[2]


In [ ]:
x[-2]

In [ ]:
x.shape = (2,5) # now x is 2-dimensional
print(x)
x[1,3]

In [ ]:
 x[1,-1]


In [ ]:
#if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array
print(x[0])

# slicing 
It is possible to slice and stride arrays to extract arrays of the same number of dimensions, but of different sizes than the original. The slicing and striding works exactly the same way it does for lists and tuples except that they can be applied to multiple dimensions as well. A few examples illustrates best:

In [ ]:
x = np.arange(10)


In [ ]:
print(x[2:5])
# space out values
print(x[2:7:2])

Note that slices of arrays do not copy the internal array data but also produce new views of the original data.
# Indexing with other arrays
It is possible to index arrays with other arrays for the purposes of selecting lists of values out of arrays into new arrays. There are two different ways of accomplishing this. One uses one or more arrays of index values. The other involves giving a boolean array of the proper shape to indicate the values to be selected. Index arrays are a very powerful tool that allow one to avoid looping over individual elements in arrays and thus greatly improve performance.

In [ ]:
#indexing arrays
x = np.arange(10,1,-1)
print(x)

x[np.array([3, 3, 1, 8])]


The index array consisting of the values 3, 3, 1 and 8 correspondingly create an array of length 4 (same as the index array) where each index is replaced by the value the index array has in the array being indexed.
Negative values are permitted and work as they do with single indices or slices:

In [ ]:

x[np.array([3, 3, -1, 8])]

In [ ]:
y = np.arange(35).reshape(5,7)
print("Y matrix")
print(y)
print("slice")
print(y[1:5:2,::3])



# Indexing Multi-dimensional arrays
Things become more complex when multidimensional arrays are indexed, particularly with multidimensional index arrays. These tend to be more unusual uses, but they are permitted, and they are useful for some problems. We’ll start with the simplest multidimensional case (using the array y from the previous examples):



  

In [ ]:
print("y =",y)
print("indexed")
y[np.array([0,2,4]), np.array([0,1,2])]

In this case, if the index arrays have a matching shape, and there is an index array for each dimension of the array being indexed, the resultant array has the same shape as the index arrays, and the values correspond to the index set for each position in the index arrays. In this example, the first index value is 0 for both index arrays, and thus the first value of the resultant array is y[0,0]. The next value is y[2,1], and the last is y[4,2].

In [ ]:
# If the index arrays do not have the same shape, there is an attempt to broadcast them to the same shape.
#If they cannot be broadcast to the same shape, an exception is raised:
print(y.shape)
y[np.array([0,2,4]), np.array([0,1])]


## Boolean or “mask” index arrays
Boolean arrays used as indices are treated in a different manner entirely than index arrays. Boolean arrays must be of the same shape as the initial dimensions of the array being indexed. In the most straightforward case, the boolean array has the same shape:

In [ ]:
y = np.arange(35).reshape(5,7)
print(y)
b=y>24
print("y values > 24")
print(y[b])

Unlike in the case of integer index arrays, in the boolean case, the result is a 1-D array containing all the elements in the indexed array corresponding to all the true elements in the boolean array. The elements in the indexed array are always iterated and returned in row-major (C-style) order.

##  Commonly  used numpy methods

In [ ]:
x = np.arange(4)
xx = x.reshape(2,2)
print(x)
print(xx)
print("shape=",xx.shape)
#ravel methods flatten a multidimension array
newarr=np.ravel(xx)
print(newarr)

In [28]:
 np.maximum([2, 3, 4], [1, 5, 2])


array([2, 5, 4])

In [29]:
np.maximum(np.eye(2), [0.5, 2]) # broadcasting

array([[1. , 2. ],
       [0.5, 2. ]])

In [30]:
np.maximum(np.Inf, 1)

inf

In [31]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)
 

array([[4, 1],
       [2, 2]])

In [40]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=a.transpose()
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [32]:
# load and show an image with Pillow
from PIL import Image
# Open the image form working directory
image = Image.open('cat.jpg')
# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)
# show the image
image.show()
#image will load in default photo viewing app


JPEG
(259, 194)
RGB


In [24]:
#convert image to rgb numbers
data = np.asarray(image)
print(type(data))
# summarize shape
print(data.shape)

<class 'numpy.ndarray'>
(194, 259, 3)


In [25]:
#see image as numbers
print(data)

[[[ 43  48  26]
  [ 46  51  31]
  [ 45  50  30]
  ...
  [164 161 146]
  [167 164 149]
  [169 166 151]]

 [[ 44  49  27]
  [ 45  50  28]
  [ 42  47  27]
  ...
  [143 139 127]
  [148 144 132]
  [153 149 137]]

 [[ 44  49  26]
  [ 43  48  26]
  [ 38  43  21]
  ...
  [106 103  94]
  [114 111 102]
  [122 119 110]]

 ...

 [[255 232 180]
  [255 239 195]
  [255 236 204]
  ...
  [ 59  84  29]
  [ 59  84  29]
  [ 59  84  29]]

 [[230 226 189]
  [253 249 212]
  [255 255 221]
  ...
  [ 84  99  56]
  [ 75  90  47]
  [ 64  79  36]]

 [[119 115  78]
  [202 198 161]
  [254 250 213]
  ...
  [ 84  99  56]
  [ 75  90  47]
  [ 64  79  36]]]


# Broadcasting

operations between differently sized arrays is called ** broadcasting **
General Broadcasting Rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

 they are equal, or
 one of them is 1

If these conditions are not met, a ValueError: frames are not aligned exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

Arrays do not need to have the same number of dimensions. For example, if you have a 256x256x3 array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. Lining up the sizes of the trailing axes of these arrays according to the broadcast rules, shows that they are compatible:

ref:https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html


# we can look through  broadcasting later
#Numpy array/matrix has a concept of Broadcasting.
import numpy as np
a = np.array([1,2,3,4])+3
print(a)
O/p => [4,5,6,7]
In above code the scalar value is added to each element of 1d array. Before addition an imaginary array is created whose size is equals to a, and elements of imaginary array is filled with b I.e

imaginary array =[3,3,3,3]
The  concept is called broadcasting.

## Difference between list and arrays in python
1.  Size in memory
2. Time for processing

In [26]:
#consider a list
import sys
import time

starttime=time.time()

l= list(range(1000))
memsize=sys.getsizeof(l)
print('mem size=',memsize)

print('finish time=',time.time()-starttime)


mem size= 9112
finish time= 0.015600204467773438


In [27]:
#consider a list
 
import time

starttime=time.time()

n=np.arange(1000)
memsize=n.size * n.itemsize
print('mem size=',memsize)

print('finish time=',time.time()-starttime)


mem size= 4000
finish time= 0.0


# END